Feature/get location
namtuthien/IE402.O21.Group2 pull request #5
Opened 2024-04-13 10:47 UTC by QuocDuy03

2024-04-13 18:26 UTC, namtuthien commented
fix conflict di

2024-04-14 08:51 UTC, QuocDuy03 commented
> fix conflict di

da fix

2024-04-14 09:22 UTC, namtuthien commented
fix conflict tiep di

2024-04-14 12:52 UTC, QuocDuy03 commented
> fix conflict tiep di

da fix part 2

2024-04-15 05:58 UTC, Devbeee commented on src/resources/scripts/pages/admin/location.js
> +fetch(`/tour/getLocations`)
thấy Mạnh cài axios rồi á, hỏi coi xài axios hay fetch :v

2024-04-15 05:58 UTC, Devbeee commented on src/routes/tour.route.js
> +router.get("/getLocations", locationController.getLocations);
location thì tạo location.route.js chứ bro, sao xoá hết route của tour ròi

2024-04-15 07:10 UTC, namtuthien commented on src/resources/scripts/pages/admin/location.js
> +fetch(`/tour/getLocations`)
tui cài axios để crawl data thui á, xài fetch như bình thường đi cho đơn giản

2024-04-15 07:13 UTC, namtuthien requested changes

2024-04-15 07:13 UTC, namtuthien commented on src/resources/views/layouts/main.hbs
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined">
hong cần link đâu, tui cài vào lun òi, coi mẫu trang / á

2024-04-15 11:39 UTC, namtuthien approved these changes

2024-04-15 14:32 UTC, Devbeee approved these changes

2024-04-15 15:13 UTC, merged